# Generated by Django 2.2.4 on 2019-10-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0021_auto_20190826_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image_quality',
            field=models.PositiveSmallIntegerField(default=95),
        ),
    ]